"""
alerts.py — Alert & Notification Module
AI Gas Stove Safety System

Centralises all alert output so you can swap in real notification methods
(sound, Telegram, SMS) without touching any other file.

Current implementations:
  • Console  — always active; prints a timestamped message.
  • Sound    — uses the `playsound` library if installed; falls back to
               the system bell (\\a) otherwise.

Stubbed-out (ready for extension):
  • Telegram bot message
  • Email / SMTP
  • Mobile push notification
  • Raspberry Pi GPIO buzzer
"""

import time
import threading


# ── Throttle: don't spam the same alert more than once per N seconds ───────
_ALERT_COOLDOWN_SECONDS = 3.0
_last_alert_time: float = 0.0          # Module-level state
_last_alert_message: str = ""


def trigger_alert(message: str) -> None:
    """
    Main entry point called by main.py when risk_level == "HIGH".

    Checks the cooldown, then fires all enabled alert channels in
    non-blocking background threads so they don't stall the video loop.

    Args:
        message: The warning text generated by logic.py.
    """
    global _last_alert_time, _last_alert_message

    now = time.time()
    same_message   = message == _last_alert_message
    within_cooldown = (now - _last_alert_time) < _ALERT_COOLDOWN_SECONDS

    # Suppress duplicate alerts within the cooldown window
    if same_message and within_cooldown:
        return

    _last_alert_time    = now
    _last_alert_message = message

    # Fire each alert channel in its own thread (non-blocking)
    _run_in_thread(_console_alert, message)
    _run_in_thread(_sound_alert)

    # Uncomment when you implement these:
    # _run_in_thread(_telegram_alert, message)
    # _run_in_thread(_email_alert, message)
    # _run_in_thread(_gpio_buzzer_alert)


# ─────────────────────────────────────────────────────────────────────────── #
#  Active alert implementations                                                #
# ─────────────────────────────────────────────────────────────────────────── #

def _console_alert(message: str) -> None:
    """
    Print a timestamped warning to the terminal.
    Always active — zero dependencies.
    """
    timestamp = time.strftime("%H:%M:%S")
    border    = "=" * 60
    print(f"\n{border}")
    print(f"  🔥  ALERT [{timestamp}]")
    print(f"  {message}")
    print(f"{border}\n")


def _sound_alert() -> None:
    """
    Play an audible alert.

    Tries `playsound` first (install via: pip install playsound==1.2.2).
    Falls back to the terminal bell character if playsound is unavailable.

    To use a custom sound file, place it at assets/alert.mp3 and update
    the SOUND_FILE path below.
    """
    SOUND_FILE = "assets/alert.mp3"  # Optional — provide your own sound file

    try:
        from playsound import playsound
        import os
        if os.path.exists(SOUND_FILE):
            playsound(SOUND_FILE, block=False)
        else:
            # playsound installed but no sound file — use bell
            print("\a", end="", flush=True)
    except ImportError:
        # playsound not installed — terminal bell fallback
        print("\a", end="", flush=True)
    except Exception as e:
        # Never let a sound failure crash the app
        print(f"[alerts] Sound error (non-fatal): {e}")


# ─────────────────────────────────────────────────────────────────────────── #
#  Stubbed future alert channels                                               #
# ─────────────────────────────────────────────────────────────────────────── #

def _telegram_alert(message: str) -> None:
    """
    FUTURE: Send a Telegram bot message.

    Steps to implement:
      1. Create a bot via @BotFather and get a BOT_TOKEN.
      2. Get your CHAT_ID by messaging your bot and calling
         https://api.telegram.org/bot<BOT_TOKEN>/getUpdates
      3. pip install python-telegram-bot
      4. Uncomment and fill in the code below.

    import telegram
    BOT_TOKEN = "your-token-here"
    CHAT_ID   = "your-chat-id-here"
    bot = telegram.Bot(token=BOT_TOKEN)
    bot.send_message(chat_id=CHAT_ID, text=f"🔥 Kitchen Alert: {message}")
    """
    pass  # Not yet implemented


def _email_alert(message: str) -> None:
    """
    FUTURE: Send an alert via email (SMTP).

    Steps to implement:
      1. Enable "Less secure app access" or generate an App Password in Gmail.
      2. Fill in SMTP_USER, SMTP_PASS, and RECIPIENT below.
      3. Uncomment the smtplib block.

    import smtplib
    from email.mime.text import MIMEText
    SMTP_HOST  = "smtp.gmail.com"
    SMTP_PORT  = 587
    SMTP_USER  = "you@gmail.com"
    SMTP_PASS  = "your-app-password"
    RECIPIENT  = "recipient@example.com"
    msg = MIMEText(f"Kitchen Alert: {message}")
    msg["Subject"] = "🔥 AI Safety Alert"
    msg["From"]    = SMTP_USER
    msg["To"]      = RECIPIENT
    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.starttls()
        server.login(SMTP_USER, SMTP_PASS)
        server.send_message(msg)
    """
    pass  # Not yet implemented


def _gpio_buzzer_alert() -> None:
    """
    FUTURE: Trigger a buzzer on Raspberry Pi via GPIO.

    Steps to implement:
      1. Wire a buzzer to a GPIO pin (e.g. pin 17).
      2. pip install RPi.GPIO
      3. Uncomment the code below.

    import RPi.GPIO as GPIO
    BUZZER_PIN = 17
    GPIO.setmode(GPIO.BCM)
    GPIO.setup(BUZZER_PIN, GPIO.OUT)
    GPIO.output(BUZZER_PIN, GPIO.HIGH)
    time.sleep(1)
    GPIO.output(BUZZER_PIN, GPIO.LOW)
    GPIO.cleanup()
    """
    pass  # Not yet implemented


def _mobile_push_alert(message: str) -> None:
    """
    FUTURE: Push notification via Pushover or Firebase Cloud Messaging (FCM).

    For Pushover (simplest option):
      1. Create an account at https://pushover.net
      2. Get your USER_KEY and create an APP_TOKEN.
      3. pip install requests
      4. Uncomment the code below.

    import requests
    USER_KEY  = "your-user-key"
    APP_TOKEN = "your-app-token"
    requests.post("https://api.pushover.net/1/messages.json", data={
        "token":   APP_TOKEN,
        "user":    USER_KEY,
        "message": f"🔥 Kitchen Alert: {message}",
        "title":   "AI Safety System"
    })
    """
    pass  # Not yet implemented


# ─────────────────────────────────────────────────────────────────────────── #
#  Internal utility                                                            #
# ─────────────────────────────────────────────────────────────────────────── #

def _run_in_thread(func, *args) -> None:
    """
    Run `func(*args)` in a daemon thread so it doesn't block the video loop.
    """
    t = threading.Thread(target=func, args=args, daemon=True)
    t.start()
