import time
import threading

from pathlib import Path
import winsound



# Throttle:

_ALERT_COOLDOWN_SECONDS = 3.0          
_last_alert_time: float = 0.0 # Module-level state
_last_alert_message: str = ""


def trigger_alert(message: str) -> None:
    """
    Main entry point called by main.py when risk_level == "HIGH".
    Checks the cooldown, then fires all alert channels in
    non-blocking background threads so they don't stall the video loop.

    Args:
        message: The warning text generated by logic.py.
    """

    global _last_alert_time, _last_alert_message

    now = time.time()

    same_message   = message == _last_alert_message
    within_cooldown = (now - _last_alert_time) < _ALERT_COOLDOWN_SECONDS

    # Suppress duplicate alerts within the cooldown window
    if same_message and within_cooldown:

        return

    _last_alert_time    = now
    _last_alert_message = message

    # Fire each alert channel in its own thread
    _run_in_thread(_console_alert, message)
    _run_in_thread(_sound_alert)

    # Uncomment when implementing telegram alert:
    # _run_in_thread(_telegram_alert, message)


# Active alert implementations

def _console_alert(message: str) -> None:
    """
    Print a timestamped warning to the terminal.
    Always active. No dependancies.
    """
    timestamp = time.strftime("%H:%M:%S")
    border    = "=" * 60
    print(f"\n{border}")
    print(f"ALERT [{timestamp}]")
    print(f"   {message}")
    print(f"{border}\n")


def _sound_alert() -> None:
    """
    Play an audible alert.

    Attempts to play the alert sound using the Windows `winsound` module.
    If the sound file is missing or an error occurs, falls back to the
    terminal bell character so the application never crashes.

    Expected file location:
        assets/audio/alert.wav
    """

    PROJECT_ROOT = Path(__file__).resolve().parent
    SOUND_FILE = PROJECT_ROOT / "assets" / "audio" / "alert.wav"

    try:

        if SOUND_FILE.exists():
            winsound.PlaySound(str(SOUND_FILE), winsound.SND_FILENAME)

        else:
            print("[alerts] Warning: alert.wav not found.")
            print("\a", end="", flush=True)

    except Exception as e:
        print(f"[alerts] Sound error (non-fatal): {e}")
        print("\a", end="", flush=True)


# Stubbed future alert channels

def _telegram_alert(message: str) -> None:
    """
    Send a Telegram bot message.

    Steps to implement:
      1. Create a bot via @BotFather and get a BOT_TOKEN.
      2. Get your CHAT_ID by messaging your bot and calling
         https://api.telegram.org/bot<BOT_TOKEN>/getUpdates
      3. pip install python-telegram-bot
      4. Uncomment and fill in the code below.

    import telegram
    BOT_TOKEN = "your-token-here"
    CHAT_ID   = "your-chat-id-here"
    bot = telegram.Bot(token=BOT_TOKEN)
    bot.send_message(chat_id=CHAT_ID, text=f"Kitchen Alert: {message}")
    """
    pass  # Not yet implemented



# Internal utility

def _run_in_thread(func, *args) -> None:
    """
    Run `func(*args)` in a daemon thread so it doesn't block the video loop.
    """
    t = threading.Thread(target=func, args=args, daemon=True)
    t.start()
